const collection = [
    {
        name: "Dune",
        director: "Denis Villeneuve",
        releaseYear: 2021,
        picture: "assets/img/Dune.jpg",
        genre: ["science-fiction"],
        cast: ["Timothée Chalamet",
            "Rebecca Ferguson",
            "Oscar Isaac",
            "Zendaya",
            "Josh Brolin",
            "Jason Momoa"],
    },
    {
        name: "Pulp Fiction",
        director: "Quentin Tarantino",
        releaseYear: 1994,
        picture: "assets/img/pulp-fiction.jpg",
        genre: ["Crime", "Drama"],
        cast: [
          "John Travolta",
          "Samuel L Jackson",
          "Uma Thurman",
          "Amanda Plummer",
        ],
      },
      {
        name: "Fight Club",
        director: "David Fincher",
        releaseYear: 1999,
        picture: "assets/img/pulp-fiction.jpg",
        genre: ["Thriller psychologique"],
        cast: [
          "Brad Pitt",
          "Edward Norton",
          "Helena Bonham Carter",
        ],
      },
      {
        name: "Le Cerlce des Poètes Disparus",
        director: "Peter Weir",
        releaseYear: 1989,
        picture: "assets/img/cercle-poete.jpg",
        genre: ["Drama"],
        cast: [
          "Robin Williams",
          "Robert Sean Leonard",
          "Ethan Hawke",
        ],
      },
      {
        name: "La Haine",
        director: "Mathieu Kassowitz",
        releaseYear: 1995,
        picture: "link/to/a/picture",
        genre: ["Drama"],
        cast: [
          "Vincent Cassel",
          "Hubert Koundé",
          "Saïd Taghmaoui",
          "Karim Belkhadra",
          "Marc Duret"
        ],
      },
      {
        name: "La 25eme Heure",
        director: "Spike Lee",
        releaseYear: 2002,
        picture: "assets/img/la25eheure.jpg",
        genre: ["Crime", "Drama"],
        cast: [
          "Edward Norton",
          "Philip Seymour Hoffman",
          "Barry Pepper",
          "Rosario Dawson",
          "Brian Cox"
        ],
      },
      {
        name: "Le Seigneur des Anneaux",
        director: "Peter Jackson",
        releaseYear: 2001,
        picture: "assets/img/SeigneurAnneau.jpg",
        genre: ["Aventure", "Drama"],
        cast: [
          "Elijah Wood",
          "Ian Mckellen",
          "Orlando Bloom",
        ],
      },
      {
        name: "Trainspotting",
        director: "Danny Boyle",
        releaseYear: 1996,
        picture: "assets/img/Trainspotting.jpg",
        genre: ["Drama"],
        cast: [
          "Ewan Mcgregor",
          "Ewen Bremner",
          "Johnny Lee Miller",
        ],
      },
      {
        name: "The Big Lebowski",
        director: "Joel Coen",
        releaseYear: 1998,
        picture: "link/to/a/picture",
        genre: ["Comedie", "Policier"],
        cast: [
          "Jeff Bridges",
          "John Goodman",
          "Julianne Moore",
          "Steve Buscemi",
        ],
      },
      {
        name: "Orange Mecanique",
        director: "Stanley Kubrick",
        releaseYear: 1971,
        picture: "link/to/a/picture",
        genre: ["Crime", "Drama"],
        cast: [
          "Malcolm McDowell",
          "Patrick Magee",
          "Michael Bates",
        ],
      },
]